# Generated by Django 5.1.4 on 2024-12-21 19:03

import phonenumber_field.modelfields
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activated_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='активированный инвайт код'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='invite_code',
            field=models.CharField(default=user.models.generate_invite_code, max_length=6, unique=True, verbose_name='инвайт код'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number', max_length=128, null=True, region=None, verbose_name='номер телефона'),
        ),
    ]
