# Generated by Django 5.1.4 on 2024-12-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='activated_invite_code',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='активированный инвайт код'),
        ),
    ]
